title: 韓国語コーパスの利用方法
description: "韓国語コーパスを検索して用例を収集するための解説サイトです"
show_excerpts: true

url: https://okikirmui.github.io/
github_username: okikirmui
author: "Yoshinori Sugai"

minima:
  social_links:
    github: okikirmui
  skin: dark

header_pages:
  - about.md

theme: minima
