title: "韓国語コーパスの使い方"
description: "韓国語コーパスを検索して用例を収集するための解説サイトです"
show_excerpts: false

url: "https://okikirmui.github.io"
lang: "ja"
markdown: kramdown
github_username: okikirmui
author: "Yoshinori Sugai"

google_analytics: UA-253677-9

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  social_links:
    github: okikirmui
header_pages:
  - overview_sejong
  - overview_yonsei
  - overview_korea

theme: minima
