title: "韓国語コーパスの使い方"
description: "韓国語コーパスを検索して用例を収集するための解説サイトです"
show_excerpts: false

url: "https://okikirmui.github.io"
lang: "ja"
markdown: kramdown
highlighter: rouge
github_username: okikirmui
author: "Yoshinori Sugai"

google_analytics: G-GQ7PMRS0P1

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  social_links:
    github: okikirmui
header_pages:
  - sejong/overview_sejong.md
  - yonsei/overview_yonsei.md
  - korea/overview_korea.md

theme: minima
