title: "韓国語コーパスの利用方法"
description: "韓国語コーパスを検索して用例を収集するための解説サイトです"
show_excerpts: false

url: "https://okikirmui.github.io"
markdown: kramdown
github_username: okikirmui
author: "Yoshinori Sugai"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# minima:
#   social_links:
#     github: okikirmui
# header_pages:
#   - about.md

# theme: minima
